export const ESTADOS_SOLICITUD = [
  "PENDIENTE_EVALUACION",
  "ACEPTADA_PENDIENTE_PUBLICACION",
  "ACEPTADA_PUBLICADA",
  "RECHAZADA",
];

export const ESTADOS_EXPEDIENTE = ["ABIERTO", "ENVIADO_AL_BOD", "PUBLICADO"];

export const TIPOS_SOLICITUD = ["PS", "FC", "EX"];
